# USING NUMPY

## Single Neuron Implementation using NUMPY

In [1]:
import numpy as np

In [3]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]

bias = 2.0

output = np.dot(inputs, weights) + bias
# output = np.dot(inputs, weights) + bias => This is also correct

print(output)

4.8


## Layers of Neurons using NUMPY

In [5]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2.0, 3.0, 0.5]

# A dot product of a matrix and a vector result on a list of dot products.
# The np.dot() method treats the matrix as a list of vectors and perform a dot product of each of those vectors with the others vector.

layer_outputs = np.dot(weights, inputs) + biases

print('Layered Output:', layer_outputs)

Layered Output: [4.8   1.21  2.385]


## Layers of Neurons and Batch of data using NUMPY

Need to take transpose of weights matrix while using numpy for batch of data.

In [6]:
inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2.0, 3.0, 0.5]

# NOTE: WE CAN'T TRANSPOSE LIST IN PYTHON, SO WE HAVE TO CONVERT WEIGHTS MATRIX INTO ARRAY FIRST
outputs = np.dot(inputs, np.array(weights).T) + biases

print('Outputs for batch of inputs:\n', outputs)

Outputs for batch of inputs:
 [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


## LECTURE - 3 => CONTINUATION

## Adding more layers to the network

In [7]:
inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2.0, 3.0, 0.5]

# Convert lists into arrays because numpy can perform matrix transposition on arrays only
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)

# Calculate the dot product and add the biases
outputs = np.dot(inputs_array, weights_array.T) + biases_array

print('Outputs for batch of inputs using arrays:\n', outputs)

Outputs for batch of inputs using arrays:
 [[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


## Layers And Batch of data using NUMPY - WITH TRANSPOSE

In [8]:
inputs = [
    [1.0, 2.0, 3.0, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2.0, 3.0, 0.5]

weights2 = [
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]
]

biases2 = [-1.0, 2.0, -0.5]

# Convert lists into arrays because numpy can perform matrix transposition on arrays only
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

# Calculate the dot product and add the biases for the first layer
layer1_outputs = np.dot(inputs_array, weights_array.T) + biases_array

# Calculate the dot product and add the biases for the second layer
layer2_outputs = np.dot(layer1_outputs, weights2_array.T) + biases2_array

print('Outputs for 2 layers and batch of inputs using arrays:\n', layer2_outputs)

Outputs for 2 layers and batch of inputs using arrays:
 [[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
